<?php

//Love this. Class fcreated by :http://biostall.com/codeigniter-google-maps-v3-api-library
//YouTube vid here: http://www.youtube.com/watch?v=Ldo6eP-EBZ8

class Maps extends CI_Controller{
	function index()
	{
		$this->load->library('googlemaps');
		
		//This likely will be auto-generated by mouse movements
		
		$config['center'] = '37.4419, -122.1419';
		$config['zoom'] = 'auto';
		$this->googlemaps->initialize($config);
		
		$marker = array();
		
		//This likely will be auto-generated by model
		$marker['position'] = '37.429, -122.1419';
		$marker['infowindow_content'] = 'hello world!';
		
		$this->googlemaps->add_marker($marker);
		
		$data['map'] = $this->googlemaps->create_map();
		
		$this->load->view('maps/maps-main', $data);
		
		print_r($data['map']['markers']);
	}
}